name: EUserv Daily Renew

on:
  schedule:
    - cron: '0 12 * * *' # 北京时间晚上8点（UTC 北京时区+8）
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run EUserv renew script
        env:
          EUSERV_EMAIL: ${{ secrets.EUSERV_EMAIL }}
          EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EUSERV_EMAIL2: ${{ secrets.EUSERV_EMAIL2 }}
          EUSERV_PASSWORD2: ${{ secrets.EUSERV_PASSWORD2 }}
          EMAIL_PASS2: ${{ secrets.EMAIL_PASS2 }}
          BARK_URL: ${{ secrets.BARK_URL }}
        run: python euser_renew.py

# --- action保活 ---
      - name: Sync Data and Keep Alive
        run: |
          date > last_run.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # add . 代表添加所有变动的文件（包括 cookies/ 文件夹和 next_renew_date.txt）
          git add .
          
          # 如果有变动才执行 commit 和 push，避免没有文件变动时报错
          if git diff --quiet && git diff --staged --quiet; then
            echo "没有需要提交的变动。"
          else
            git commit -m "Auto update: $(date)"
            git push
          fi
